# Generated by Django 4.1 on 2022-11-09 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Headline')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=500, populate_from='title')),
                ('status', models.CharField(choices=[('daft', 'Draft'), ('published', 'Published'), ('submitforreview', 'Submitted for Review'), ('hidden', 'Hidden'), ('archived', 'Archived'), ('readytopublish', 'Ready to publish'), ('scheduled', 'Scheduled')], default='daft', max_length=50)),
                ('number_of_comments', models.PositiveIntegerField(default=0)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.CharField(default='media-manager/2020/02/12/placeholder-960x540.jpg', help_text='Path to an image', max_length=250, null=True)),
                ('cover_image_description', models.CharField(blank=True, max_length=500, null=True)),
                ('page_title', models.CharField(max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.articlecategory')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'permissions': [('can_publish_article', 'Can publish the article'), ('can_save_draft', 'Can save the article as draft'), ('can_submit_for_review', 'Can submit the article for review'), ('can_submit_for_publishing', 'Can submit the article for publishing'), ('can_edit_article', 'Can edit the article'), ('can_preview_article', 'Can preview article'), ('view_all_articles', 'View all articles'), ('can_unpublish_article', 'Can unpublish article'), ('can_view_article_history', 'Can View Article History'), ('can_schedule_articles', 'Can Schedule Articles for Publishing')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=200, populate_from='name', unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
                ('page_type', models.CharField(choices=[('home-page', 'Home'), ('detail-page', 'Detail'), ('demo-page', 'Demo')], default='', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('inactive', 'Inactive')], max_length=50)),
                ('layout', models.TextField(help_text='layout html text of the page')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'permissions': [('can_edit_page', 'Can edit page'), ('can_modify_page', 'Modify page'), ('can_duplicate_and_edit_page', 'Duplicate and Edit page'), ('can_view_page_list', 'View Page List'), ('can_view_page_code', 'View Page Code'), ('can_edit_home_page', 'Can Edit Home Page'), ('can_edit_category_page', 'Can Edit Category Page')],
                'get_latest_by': 'last_changed_date',
            },
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='ArticleTag',
        ),
        migrations.CreateModel(
            name='LeadNewsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'verbose_name': 'Lead news history',
                'verbose_name_plural': 'Lead news history',
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='LeadNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('position', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=10, unique=True)),
                ('fixed_lead', models.BooleanField(default=False)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'verbose_name': 'Lead news',
                'verbose_name_plural': 'Lead news',
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('daft', 'Draft'), ('published', 'Published'), ('submitforreview', 'Submitted for Review'), ('hidden', 'Hidden'), ('archived', 'Archived'), ('readytopublish', 'Ready to publish'), ('scheduled', 'Scheduled')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('other_changes', models.JSONField(blank=True, help_text='json. A json containing the article edit history', null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.articletag'),
        ),
    ]
