# Generated by Django 4.1 on 2022-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_cover_image_alter_leadnews_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.CharField(default='media-manager/2020/02/12/placeholder-960x540.jpg', help_text='Path to an image', max_length=250, null=True),
        ),
    ]
