# Generated by Django 4.1 on 2022-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(help_text='Path to an image', max_length=250, null=True, upload_to='articles/'),
        ),
    ]
