# Generated by Django 4.1 on 2022-11-16 09:05

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_page_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('youtube', 'Youtube'), ('video', 'video')], max_length=200)),
                ('youtube_link', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='articles.articlecategory'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home-page', 'Home'), ('detail-page', 'Detail'), ('category-page', 'Category'), ('video-page', 'video')], default='', max_length=20),
        ),
    ]
