# Generated by Django 4.1 on 2022-11-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_videos_alter_article_category_alter_page_page_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videos',
            new_name='video',
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
    ]
