# Generated by Django 4.1 on 2022-11-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_videos_video_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('youtube', 'Youtube'), ('video', 'video')], max_length=200, null=models.CharField(db_index=True, max_length=500, verbose_name='Headline')),
            preserve_default=models.CharField(db_index=True, max_length=500, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='article',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
