# Generated by Django 4.1 on 2022-11-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
