# Generated by Django 4.1 on 2022-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('default', 'Default'), ('gallery', 'Gallery'), ('video', 'Video')], default='default', max_length=50),
        ),
    ]
