# Generated by Django 4.1 on 2022-11-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Trending_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='latest_article',
            field=models.BooleanField(default=False),
        ),
    ]
