# Generated by Django 4.1 on 2022-11-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_trending_article_article_latest_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Trending_article',
            new_name='trending_article',
        ),
    ]
