# Generated by Django 4.1 on 2022-11-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_rename_trending_article_article_trending_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home-page', 'Home'), ('detail-page', 'Detail'), ('category-page', 'Category'), ('video-page', 'video'), ('Tag-page', 'Tag')], default='', max_length=20),
        ),
    ]
