# Generated by Django 4.1 on 2022-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_alter_page_page_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="feature_article",
            field=models.BooleanField(default=False),
        ),
    ]
