# Generated by Django 4.1 on 2022-11-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0017_article_feature_article"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="category",),
        migrations.DeleteModel(name="ArticleCategory",),
    ]
