# Generated by Django 4.1 on 2022-11-26 07:48

import colorfield.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0018_remove_article_category_delete_articlecategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="Name English"),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#eb6734", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name_en", unique=True
                    ),
                ),
                ("show_in_content_editor", models.BooleanField(default=True)),
                ("show_in_level_1", models.BooleanField(default=False)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="category-icons/"
                    ),
                ),
                ("img_code", models.CharField(blank=True, max_length=800, null=True)),
            ],
            options={
                "verbose_name": "Article Category",
                "verbose_name_plural": "Article Categories",
                "permissions": [("can_edit_category", "Can edit Category")],
            },
        ),
    ]
