# Generated by Django 4.1.3 on 2022-12-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0020_article_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="site_cofig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
